# spark-operator-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflow-sparkoperator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/version: __sparkOperator.image__
  template:
    metadata:
      labels:
        app.kubernetes.io/version: __sparkOperator.image__
    spec:
      containers:
        - name: sparkoperator
          image: lightbend/sparkoperator:__sparkOperator.image__
          args:
            - -v=2
            - -namespace=
            - -ingress-url-format=
            - -controller-threads=10
            - -resync-interval=30
            - -logtostderr
            - -enable-metrics=true
            - -metrics-labels=app_type
            - -metrics-port=10254
            - -metrics-endpoint=/metrics
            - -metrics-prefix=
            - -enable-webhook=true
            - -webhook-svc-namespace=__namespace__
            - -webhook-port=8080
            - -webhook-svc-name=cloudflow-webhook
            - -webhook-config-name=cloudflow-sparkoperator-webhook-config
          resources:
            limits:
              cpu: "1"
              memory: 1024M
            requests:
              cpu: 100m
              memory: 512M
